### ISSUE TITLE
Invalid redirect when installing on 2021-06-22

### ISSUE THREAD

**Issue by MichaelMahlberg** [MichaelMahlberg/mirometrics#4]
We couldn't install this app
Invalid redirect: <b>https://miroplugins.devisive.de/kanbantesting/success.html</b> does not match one of the registered values:<br> https://miroplugins.devisive.de/flowmetrics/install.php<br>https://miroplugins.devisive.de/flowmetrics/success.html

**Comment by agiledivider** [comment]
fixed it in the documentation the correct installation link at the moment is:
https://miro.com/oauth/authorize/?response_type=code&client_id=3074457348136685529&redirect_uri=https%3A%2F%2Fmiroplugins.devisive.de%2Fflowmetrics%2Finstall.php
